<?php

namespace LF\UserBundle\Repository;

/**
 * ConnectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionsRepository extends \Doctrine\ORM\EntityRepository
{
}
