<?php

namespace LF\EventBundle\Repository;

/**
 * ViewedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewedRepository extends \Doctrine\ORM\EntityRepository
{
}
