lf_event_homepage:
    path:     /{id}
    defaults: { _controller: LFEventBundle:Default:index }
    requirements:
        id: \d+

lf_event_theme:
    path:     /theme/{id}
    defaults: { _controller: LFEventBundle:Default:theme }
    requirements:
        id: \d+

lf_event_archive:
    path:     /archive/{page}
    defaults: { _controller: LFEventBundle:Default:archive , page: 1 }
    requirements:
        page: \d+

# lf_event_theme:
#     path:     /theme_menu
#     defaults: { _controller: LFEventBundle:Themes:getAllThemesMenu }
#     requirements:
#         id: \d+